### ISSUE TITLE
temperature offset conversion

### ISSUE THREAD

**Issue by MatthiasN73** [tiagolobao/CS5490#12]
Hello Tiago, 
I’am using your library in my wifi energy meter project. Great work, saved me a lot of time dealing with cs5490. But I have an issue with the temperature offset. Reading the cs5490 datasheet I found “… with the binary point to the right of bit 16.”, but in the library you have “toBinary(23,MSBsigned,value);”. Can you check this.

**Comment by tiagolobao** [comment]
Hello Matthias!
Yeah you are right, I'll fix it. Thanks!! : )
